#include <environment/EnvironmentInformation.h>
#include <environment/SpaceDiscretization.h>
#include <environment/AdjacencyEnvironment.h>
#include <environment/RewardMap.h>
#include <environment/ObstacleMap.h>
#include <environment/Feature.h>
#include <environment/GridBasedBodyAdjacency.h>
#include <environment/RewardMap.h>
#include <environment/BodyOrientationFeature.h>
#include <environment/CurvatureFeature.h>
#include <environment/HeightDeviationFeature.h>
#include <environment/KinematicFeasibilityFeature.h>
#include <environment/LatticeBasedBodyAdjacency.h>
#include <environment/LegCollisionFeature.h>
#include <environment/PotentialBodyOrientationFeature.h>
#include <environment/PotentialLegCollisionFeature.h>
#include <environment/SlopeFeature.h>
#include <environment/StancePostureFeature.h>
#include <environment/SupportTriangleFeature.h>
