#include <model/Model.h>
#include <model/Constraint.h>
#include <model/Cost.h>
#include <model/WholeBodyDynamics.h>
#include <model/WholeBodyKinematics.h>
#include <model/FullDynamicSystem.h>
#include <model/KinematicConstraints.h>
#include <model/RobCoGenWholeBodyDynamics.h>
#include <model/RobCoGenWholeBodyKinematics.h>
#include <model/StabilityConstraints.h>
