#include <dwl/model/OptimizationModel.h>
#include <dwl/model/Constraint.h>
#include <dwl/model/Cost.h>
#include <dwl/model/WholeBodyDynamics.h>
#include <dwl/model/WholeBodyKinematics.h>
#include <dwl/model/FullDynamicalSystem.h>
#include <dwl/model/CentroidalDynamicalSystem.h>
#include <dwl/model/KinematicConstraint.h>
#include <dwl/model/RobCoGenWholeBodyDynamics.h>
#include <dwl/model/RobCoGenWholeBodyKinematics.h>
#include <dwl/model/StabilityConstraint.h>
